classname: tsdat.io.retrievers.StorageRetriever
parameters:
  fetch_parameters:
    # How far in time to look after the "end" timestamp (+), before the "begin"
    # timestamp (-), or both (none) to find filenames that contain needed data
    time_padding: -48h

coords:
  time:
    name: time
  time_gps:
    name: time_gps
  time_sst:
    name: time_sst
  time_baro:
    name: time_baro
  time_met:
    name: time_met
  time_pwr:
    name: time_pwr
  frequency:
    name: frequency
  direction:
    name: direction

data_vars:
  x:
    .*:
      name: x
  y:
    .*:
      name: y
  z:
    .*:
      name: z
  latitude:
    .*:
      name: latitude
  longitude:
    .*:
      name: longitude
  sea_surface_temperature:
    .*:
      name: sea_surface_temperature
  air_temperature:
    .*: 
      name: air_temperature
  humidity: 
    .*: 
      name: humidity
  air_pressure:
    .*:
      name: air_pressure
