classname: pipelines.vap_fourier_vs_wavelet.pipeline.VapWaves
parameters:
  datastreams:
    - clallam.spotter-pos-400ms.a1

triggers: []

retriever:
  path: pipelines/vap_fourier_vs_wavelet/config/retriever.yaml

dataset:
  path: pipelines/vap_fourier_vs_wavelet/config/dataset.yaml

quality:
  path: pipelines/vap_fourier_vs_wavelet/config/quality.yaml

storage:
  path: shared/storage.yaml
